### ISSUE TITLE
A valid environment variable to satisfy the declaration 'env:SLACK_INCOMMING_WEBHOOK_URL' could not be found.

### ISSUE THREAD

**Issue by kkashyap1707** [kamataryo/aws-billing-alert#7]
A valid environment variable to satisfy the declaration 'env: SLACK_INCOMMING_WEBHOOK_URL' could not be found.

<img width="1723" alt="Screenshot 2021-05-25 at 9 23 20 PM" src="https://user-images.githubusercontent.com/4715140/119529137-72e51e80-bd9f-11eb-810a-856db7a9a9b1.png">

I entered in .envrc

export SLACK_INCOMMING_WEBHOOK_URL=https://hooks.slack.com/services/T0*********T/B*******1TLH/**********************

**Comment by kamataryo** [comment]
@kkashyap1707 HI, thanks for reporting!
Have you installed [direnv](https://github.com/direnv/direnv)? Without direnv, you can run the stack with the command below:

```shell
$ source .envrc # spread the variables with your environment
$ npm run deploy
```

Or simply you can run:

```shell
SLAVK_INCOMMING_WEBHOOK_URL=https://hooks.slack.com/services/*** npm run deploy
```

Please try them!
